apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdbrain
  namespace: birdbrain
  labels:
    app: birdbrain
spec:
  selector:
    matchLabels:
      app: birdbrain
  template:
    metadata:
      labels:
        app: birdbrain
    spec:
      containers:
        - name: birdbrain
          image: ghcr.io/unitybirb/birdbrain:main
          imagePullPolicy: Always
          env:
           - name: DISCORD_TOKEN
             valueFrom:
              secretKeyRef:
                name: discord-token-secret
                key: discord-token
      imagePullSecrets:
        - name: github-container-registry



